from extract import extract_csv
from utils import setup_logger
from transform import transformCustomersData,transformOrdersData,transformProductsData,transformSalesData
from load import createConnection,load_data
from incremental import get_last_loaded_date,update_last_loaded_date,filter_incremental_data
logger =setup_logger()

def main():
    try:
        print("ETL Pipeline Started")
        logger.info(f"Extraction of Data Started")
        customers_df = extract_csv("data/raw/customers.csv",["customer_id","first_name","last_name","email"])
        logger.info(f"Customers Data Piped :{len(customers_df)} rows")
        products_df = extract_csv("data/raw/products.csv",["product_id","product_name","category","price"])
        logger.info(f"Products Data Piped :{len(products_df)} rows")
        orders_df = extract_csv("data/raw/orders.csv",["order_id","customer_id","order_date","amount"])
        logger.info(f"Orders Data Piped :{len(orders_df)} rows")
        sales_df = extract_csv("data/raw/sales.csv",["sale_id","order_id","product_id","quantity","sale_amount"])
        logger.info(f"Sales Data Piped :{len(sales_df )} rows")
        logger.info("Extraction of Data Ended")
        #print("Transformation Data Started")
        logger.info(f"Transform Data Started")
        transformed_customers_df = transformCustomersData(customers_df)
        logger.info(f"Transformed Customers Data :{len(transformed_customers_df)} rows")
        transformed_products_df = transformProductsData(products_df)
        logger.info(f"Transformed Products Data :{len(transformed_products_df)} rows")
        transformed_orders_df = transformOrdersData(orders_df)
        logger.info(f"Transformed Orders Data :{len(transformed_orders_df)} rows")
        transform_sales_df = transformSalesData(sales_df)
        logger.info(f"Transformed Sales Data :{len(transform_sales_df )} rows")
        logger.info("Transform Data Ended")
        #print("Transformation Data Ended")
        
        logger.info(f"Creating the DB Connection")
        connection = createConnection()
        #print("Loading of Transformed Data Started")
        logger.info(f"Loading of Data Started")
        GetCustomersLastLoadedDate = get_last_loaded_date("customers",connection)
        transformed_customers_df = filter_incremental_data(transformed_customers_df,"updated_date",GetCustomersLastLoadedDate)
        logger.info(f"Filtered Customers Data for Incremental Load :{len(transformed_customers_df)} rows")
        load_data(transformed_customers_df,"customers",connection)
        logger.info(f"Loaded Customers Data :{len(transformed_customers_df)} rows")
        update_last_loaded_date("customers",connection)
        logger.info(f"Updated last loaded date for customers table")
        GetProductsLastLoadedDate = get_last_loaded_date("products",connection)
        transformed_products_df = filter_incremental_data(transformed_products_df,"added_date",GetProductsLastLoadedDate)
        logger.info(f"Filtered Products Data for Incremental Load :{len(transformed_products_df)} rows")
        load_data(transformed_products_df,"products",connection)
        logger.info(f"Loaded Products Data :{len(transformed_products_df)} rows")
        update_last_loaded_date("products",connection)
        logger.info(f"Updated last loaded date for products table")
        GetOrdersLastLoadedDate = get_last_loaded_date("orders",connection)
        transformed_orders_df = filter_incremental_data(transformed_orders_df,"added_date",GetOrdersLastLoadedDate)
        logger.info(f"Filtered Orders Data for Incremental Load :{len(transformed_orders_df)} rows")
        load_data(transformed_orders_df,"orders",connection)
        logger.info(f"Loaded Orders Data :{len(transformed_orders_df)} rows")
        update_last_loaded_date("orders",connection)
        logger.info(f"Updated last loaded date for orders table")
        GetSalesLastLoadedDate = get_last_loaded_date("sales",connection)
        transformed_sales_df = filter_incremental_data(transform_sales_df,"last_updated",GetSalesLastLoadedDate)
        logger.info(f"Filtered Sales Data for Incremental Load :{len(transformed_sales_df)} rows")
        load_data(transformed_sales_df,"sales",connection)
        logger.info(f"Loaded Sales Data :{len(transformed_sales_df )} rows")
        update_last_loaded_date("sales",connection)
        logger.info(f"Updated last loaded date for sales table")
        logger.info("Loading of Data Ended")
        #print("Loading of Transformed Data Ended")
        
        print("ETL Pipeline Ended")

    except Exception as e:
        logger.error(f"Error {str(e)} ")

if __name__== "__main__":
    main()